improved: loading targets from json
added: targets matrix in json

diff --git a/.github/workflows/ctr_workspace_cuda.yml b/.github/workflows/ctr_workspace_cuda.yml
--- a/.github/workflows/ctr_workspace_cuda.yml
+++ b/.github/workflows/ctr_workspace_cuda.yml
@@ -7,64 +7,28 @@ env:
   TOKEN: ${{ secrets.PACKAGE_TOKEN }}
 
 jobs:
+  load-targets:
+    runs-on: ubuntu-latest
+    outputs:
+      targets: ${{ steps.set-data.outputs.targets }}
+    steps:
+      - uses: actions/checkout@v3
+      - id: set-data
+        working-directory: ./CTR_WORKSPACE
+        run: |
+          fp=./targets_matrix.json
+          if [ -e $fp ]; then
+            echo "targets=$(cat $fp | jq -c)" >> $GITHUB_OUTPUT
+          else
+            echo "$fp not found"
+            exit 1
+          fi
   build-and-push-to-ghcr:
+    needs: load-targets
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
-      matrix:
-        include:
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: ''
-            cuda_version: 10.1
-            base_ubuntu: 18.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: ''
-            cuda_version: 10.2
-            base_ubuntu: 18.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: 11.1
-            cuda_version: 11.1.1
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: ''
-            cuda_version: 11.2.0
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: ''
-            cuda_version: 11.2.1
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: 11.2
-            cuda_version: 11.2.2
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: ''
-            cuda_version: 11.3.0
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: 11.3
-            cuda_version: 11.3.1
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: ''
-            cuda_version: 11.5.0
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: ''
-            cuda_version: 11.5.1
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: 11.5
-            cuda_version: 11.5.2
-            base_ubuntu: 20.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: 11.7
-            cuda_version: 11.7.1
-            base_ubuntu: 22.04
-          - dockerfile: ./CTR_WORKSPACE/ws.cuda.dockerfile
-            extra_tags: 11.8,latest
-            cuda_version: 11.8.0
-            base_ubuntu: 22.04
+      matrix: ${{ fromJSON(needs.load-targets.outputs.targets) }}
     env:
       REGISTRY: ghcr.io
       IMAGE_NAME: workspace
